name: EC2 Runner Workflow

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1  # Change this to your desired region
  INSTANCE_TYPE: t2.micro  # Change this to your desired instance type
  AMI_ID: ami-04b4f1a9cf54c11d0  # Amazon Linux 2 AMI ID

jobs:
  run-on-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Create temporary key pair
      id: create-key-pair
      run: |
        # Create a temporary key pair
        KEY_NAME="github-action-$(date +%s)"
        aws ec2 create-key-pair --key-name "$KEY_NAME" --query 'KeyMaterial' --output text > private_key.pem
        chmod 600 private_key.pem
        echo "key_name=$KEY_NAME" >> $GITHUB_ENV
    
    - name: Launch EC2 instance
      id: launch-ec2
      run: |
        # Launch the instance and capture its ID
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ${{ env.AMI_ID }} \
          --instance-type ${{ env.INSTANCE_TYPE }} \
          --key-name ${{ env.key_name }} \
          --security-group-ids ${{ secrets.AWS_SECURITY_GROUP }} \
          --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
          --associate-public-ip-address \
          --block-device-mappings '[{"DeviceName":"/dev/xvda","Ebs":{"VolumeSize":8,"DeleteOnTermination":true}}]' \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GithubActionRunner}]' \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
        
        # Wait for instance to be running
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        
        # Get public IP and ensure it's set with increased timeout
        MAX_ATTEMPTS=30
        ATTEMPT=1
        
        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "Attempt $ATTEMPT of $MAX_ATTEMPTS to get public IP..."
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          
          if [ "$PUBLIC_IP" != "None" ] && [ -n "$PUBLIC_IP" ]; then
            echo "Public IP obtained: $PUBLIC_IP"
            echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV
            break
          fi
          
          if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
            echo "Failed to get public IP after $MAX_ATTEMPTS attempts"
            exit 1
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
          sleep 10
        done
        
        # Wait for SSH to be available with increased timeout
        echo "Waiting for SSH to become available at $PUBLIC_IP..."
        MAX_SSH_ATTEMPTS=30
        SSH_ATTEMPT=1
        
        while [ $SSH_ATTEMPT -le $MAX_SSH_ATTEMPTS ]; do
          echo "SSH connection attempt $SSH_ATTEMPT of $MAX_SSH_ATTEMPTS..."
          if nc -z -w 5 $PUBLIC_IP 22; then
            echo "SSH is available!"
            break
          fi
          
          if [ $SSH_ATTEMPT -eq $MAX_SSH_ATTEMPTS ]; then
            echo "Failed to establish SSH connection after $MAX_SSH_ATTEMPTS attempts"
            exit 1
          fi
          
          SSH_ATTEMPT=$((SSH_ATTEMPT + 1))
          sleep 10
        done
    
    - name: Run Python script on EC2
      run: |
        # Copy files to EC2
        scp -i private_key.pem -o StrictHostKeyChecking=no \
          *.py requirements.txt* ec2-user@${PUBLIC_IP}:~/
        
        # Create and copy setup script
        cat << 'EOF' > setup.sh
        #!/bin/bash
        sudo yum update -y
        sudo yum install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
          python3 -m pip install -r requirements.txt
        fi
        EOF
        
        chmod +x setup.sh
        scp -i private_key.pem -o StrictHostKeyChecking=no setup.sh ec2-user@${PUBLIC_IP}:~/
        
        # Setup Python environment and run script
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${PUBLIC_IP} \
          "cd ~/ && chmod +x setup.sh && ./setup.sh && python3 *.py > output.txt 2>&1"
        
        # Get the results back
        scp -i private_key.pem -o StrictHostKeyChecking=no \
          ec2-user@${PUBLIC_IP}:~/output.txt ./
    
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-script-results
        path: output.txt
    
    - name: Cleanup
      if: always()  # Run even if previous steps failed
      run: |
        # Terminate the instance
        if [ -n "$INSTANCE_ID" ]; then
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
          aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}
        fi
        
        # Delete the temporary key pair
        if [ -n "${{ env.key_name }}" ]; then
          aws ec2 delete-key-pair --key-name ${{ env.key_name }}
        fi
        
        # Remove the private key file
        rm -f private_key.pem 